---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tonetag-cert
spec:
  secretName: tonetag-cert
  commonName: tonetag.is
  dnsNames:
    - tonetag.is
  issuerRef:
    name: tonetag-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...